export * from '../../routes/admin.routes.js'
export * from '../../routes/auth.routes.js'
export * from '../../routes/hall.routes.js'
export * from '../../routes/me.routes.js'
export * from '../../routes/meta.routes.js'
export * from '../../routes/solution.routes.js'
export * from '../../routes/sprint.routes.js'
export * from '../../routes/submission.routes.js'
