-- AlterTable
ALTER TABLE "User" ADD COLUMN "realName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN "stack" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "User" ADD COLUMN "moneyEarned" INTEGER NOT NULL DEFAULT 0;
